#!/usr/bin/env python
"""
This script attempts to enumerate cold fusion administrative interfaces
usage: cat <targetfile> | xargs -Px -I % python xargs_cf_enum1_0.py %

"""
import requests
from requests.exceptions import ConnectionError
import sys
if len(sys.argv) != 2:
	print("Target not specified! Usage: cat <targetfile> | xargs -Px -I % python xargs_cf_enum1_0.py %")
	sys.exit(0)
host = sys.argv[1]

cfide_admin_path = '/CFIDE/administrator/index.cfm'
r = 'http://' + host + cfide_admin_path
try:
    results=requests.get(r, allow_redirects=True, verify=False, timeout=0.5)
#	print(r.url)
    if results.status_code == 200:
        f = open('cfwork.txt', 'a')
	print(results.url)
        f.write(results.url + "\r\n")
        f.close()
    else:
        sys.exit(0)
except requests.exceptions.RequestException as e:
    print e
